
services:
  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:15-alpine
    env_file:
      - .env
    command:
      - 'postgres'
      - '-c'
      - 'port=${POSTGRES_PORT}'
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - server_net
      
  database_service:
    container_name: ${DATABASE_SERVICE_HOST}
    build: ./database_service
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - server_net

  products_service:
    container_name: ${PRODUCTS_SERVICE_HOST}
    build: ./products_service
    env_file:
      - .env
    networks:
      - server_net

  requests_service:
    container_name: ${REQUEST_SERVICE_HOST}
    build: ./requests_service
    env_file:
      - .env
    networks:
      - server_net

  users_service:
    container_name: ${USERS_SERVICE_HOST}
    build: ./users_service
    env_file:
      - .env
    networks:
      - server_net

  react_app:
    container_name: ${REACT_APP_HOST}
    build: ./react_app
    env_file:
      - .env
    networks:
      - server_net

  nginx:
    container_name: ${NGINX_HOST}
    build: ./nginx
    restart: on-failure
    ports:
      - ${NGINX_PORT}:${NGINX_PORT}
    depends_on:
      - react_app
      - users_service
      - requests_service
      - products_service
      - database_service
    env_file:
      - .env
    networks:
      - server_net

volumes:
  db_vol: {}

networks:
  server_net:
    driver: bridge